---
- name: Add Bareos GPG Key
  apt_key:
    url: "{{ bareos_url_debian }}/Release.key"
    state: present

- name: Add Bareos Repository
  apt_repository:
    repo: "deb {{ bareos_url_debian }} /"
    state: present
  loop:

- name: update apt cache
  apt:
    update_cache: yes

- name: Install Bareos Client
  apt:
    name: "{{ debian_pkgs }}"

- name: Include Client Configuration - Server side
  include_tasks: server-configuration.yml

- name: Template Client Configuration - Client side
  template:
    src: bareos-dir.conf.j2
    dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
    owner: bareos
    group: bareos
    mode: 0640
  notify:
    - restart bareos_client
#  register: client_archive
