- include_tasks: RedHat.yml
  when: ansible_distribution == 'CentOS'
#  when: ansible_os_family == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_distribution == 'Debian'
#  when: ansible_os_family == 'Debian'

- include_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
