---
- name: Check if Bareos repo is already configured.
  stat: path="{{ repo_bareos_file_path }}"
  register: repo_bareos_file_result

- name: Set Bareos repo for RHEL/CentOS
  yum_repository:
    name: bareos
    description: 'bareos repo details'
    baseurl: "http://download.bareos.org/bareos/{{ repo_bareos_release }}/{{ repo_bareos_distro }}/"
    gpgcheck: yes
    gpgkey: "http://download.bareos.org/bareos/{{ repo_bareos_release }}/{{ repo_bareos_distro}}/repodata/repomd.xml.key"
    enabled: yes
    state: present
  when:
    - not repo_bareos_file_result.stat.exists

- name: Install Bareos Client
  yum:
    name: "{{ rhel_pkgs }}"

- name: Template Client Configuration
  template:
    src: client-fd.conf.j2
    dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
    owner: bareos
    group: bareos
    mode: 0640
  notify:
    - restart bareos_client
