- hosts: [server]
  tasks:
    - name: Template Client Configuration - Server side
      template:
        src: client-fd.conf.j2
        dest: /etc/bareos/bareos-dir.d/client/{{ client_name }}-fd.conf
        owner: bareos
        group: bareos
        mode: 0640
      notify:
        - restart bareos_server
