---
- name: Add Bareos GPG Key
  apt_key:
    url: "{{ bareos_url_ubuntu }}/Release.key"
    state: present
#  loop:
#    - http://download.bareos.org/bareos/release/18.2/Release.gpg

- name: Add Bareos Repository
  apt_repository:
    repo: "deb {{ bareos_url_ubuntu }} /"
    state: present
  loop:

- name: update apt cache
  apt:
    update_cache: yes

- name: Install Bareos Client
  apt:
    name: "{{ ubuntu_pkgs }}"

- name: Include Client Configuration - Server side
  include_tasks: server-configuration.yml

- name: Template Client Configuration - Client side
  template:
    src: bareos-dir.conf.j2
    dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
    owner: bareos
    group: bareos
    mode: 0640
  notify:
    - restart bareos_client

#- name: Checking if client template exists
#   command: ls /etc/bareos/bareos-fd.d/director/bareos-dir.conf
#   register: client_archive
