---
# handlers file for roles
- name: restart bareos_server
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - bareos-fd
    - bareos-dir
    - bareos-sd

- name: restart bareos_client
  service:
    name: bareos-fd
    state: restarted
    enabled: yes

# - name: restart bareos-dir
#   service:
#     name: bareos-dir
#     state: restarted
#     enabled: yes
